// UTD Majors (2025 Undergraduate Catalog)
export const utdMajors = [
  "Animation and Games",
  "Media Arts and Design",
  "History",
  "Latin American Studies",
  "Literature",
  "Philosophy",
  "Professional Communication and Digital Media Studies",
  "Visual and Performing Arts",
  "Child Learning and Development",
  "Cognitive Science",
  "Neuroscience",
  "Psychology",
  "Speech, Language, and Hearing Sciences",
  "Criminology",
  "Economics",
  "International Political Economy",
  "Public Health",
  "Political Science",
  "Sociology",
  "Computational and Geospatial Science",
  "Geospatial Information Sciences",
  "Public Affairs",
  "Public Policy",
  "Sustainability Planning and Policy",
  "Biomedical Engineering",
  "Computer Engineering",
  "Computer Science",
  "Data Science",
  "Electrical Engineering",
  "Mechanical Engineering",
  "Software Engineering",
  "Systems Engineering",
  "American Studies",
  "Education",
  "Interdisciplinary Studies",
  "Healthcare Studies",
  "Accounting",
  "Business Administration",
  "Business Analytics and Artificial Intelligence",
  "Computer Information Systems and Technology",
  "Cybersecurity and Risk Management",
  "Finance",
  "Global Business",
  "Healthcare Management",
  "Human Resource Management",
  "Marketing",
  "Supply Chain Management and Analytics",
  "Biology",
  "Chemistry",
  "Mathematics",
  "Physics",
  "Actuarial Science",
  "Biochemistry",
  "Biomedical Sciences",
  "Geosciences",
  "Molecular Biology"
];
